INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Puu- ja köögiviljad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Lihatooted');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'kalatooted');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Piimatooted');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Munad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Võid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Juustud');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Leivad, saiad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Kondiitritooted');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Valmistoidud');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Kuivained');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Hommikusöögid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Hoidised');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Maailma köök');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Maitseained');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Puljongid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Kastmed, õlid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Maiustused');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Küpsised');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Näksid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Külmutatud toidukaubad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Joogid');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Lastekaubad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Lemmikloomakaubad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Enesehooldustarbed');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Majapidamistarbed');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Vabaajakaubad');
INSERT INTO public.ingredient_group (id, name) VALUES (DEFAULT, 'Hooajakaubad');

INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Grillretseptid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Hommikusöögid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Joogid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Kala ja mereannid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Kana');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Kastmed, määrded');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Magustoidud');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Magusad küpsetised');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Eelroad');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Leib, Sai');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Liha');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Linnuliha');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Pastad ja risotod');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Salatid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Soolased küpsetised');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Supid');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Suupisted');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Vormiroad');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Võileivad');
INSERT INTO public.recipe_category (id, name) VALUES (DEFAULT, 'Taimetoidud');

INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'tk', 'tükk');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'ml', 'milliliiter');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'dl', 'detsiliiter');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'l', 'liiter');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'g', 'gramm');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'kg', 'kilogramm');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'tl', 'teelusikas');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'spl', 'supilusikas');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'pudel', 'valmis toote pudel');
INSERT INTO public.measurement_unit (id, name, description) VALUES (DEFAULT, 'purk', 'valmis toote purk');

INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '0-15 min');
INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '16-30 min');
INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '31-45 min');
INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '46-60 min');
INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '1-2 h ');
INSERT INTO public.preparation_time (id, prep_time) VALUES (DEFAULT, '2+ h');

INSERT INTO public."user" (id, username, password) VALUES (DEFAULT, 'Mairold', '123');
INSERT INTO public."user" (id, username, password) VALUES (DEFAULT, 'Kristiina', '123');
INSERT INTO public."user" (id, username, password) VALUES (DEFAULT, 'Helen', '123');


